### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference (render.go)

### ISSUE THREAD

**Issue by mirkomikulic** [relops/cqlc#18]
I'm seeing occasional nil pointer dereferences in render.go (line 81) that causes my entire webapp to crash: 

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x30 pc=0x708767]

goroutine 4573 [running]:
github.com/relops/cqlc/cqlc.renderInsert(0xc208083ce0, 0xc210e55ab0)
	/home/ubuntu/go/src/github.com/relops/cqlc/cqlc/render.go:81 +0x77
github.com/relops/cqlc/cqlc.(*Context).RenderCQL(0xc208083ce0, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/relops/cqlc/cqlc/cqlc.go:570 +0x1c1
github.com/relops/cqlc/cqlc.BuildStatement(0xc208083ce0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/relops/cqlc/cqlc/cqlc.go:525 +0x8a
github.com/relops/cqlc/cqlc.(*Context).Exec(0xc208083ce0, 0xc208094160, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/relops/cqlc/cqlc/cqlc.go:464 +0x43

**Comment by 0x6e6562** [comment]
Thanks for reporting this - do you have an example that we can use to reproduce the issue?

**Comment by mirkomikulic** [comment]
Unfortunately not really. That happens on a regular insert. 
It usually happens after a couple of hours of runtime. I'm using negroni and negronicql. 

I was thinking that maybe the connection to cassandra gets dropped - but I'm not really sure. 

It's also interesting why the entire webapp crashes, not just the current goroutine.

**Comment by mirkomikulic** [comment]
I think I got it: 
I had a race condition in which the context was being shared. :/ silly me. 

I'll open another issue should this issue still arise. Thanks a lot!

**Comment by 0x6e6562** [comment]
The docs aren't very clear about the thread safety of the context object, so maybe this issue indicates that the docs require some improvement.

Basically the context instance is inherently not thread safe because it needs to accumulate state to build the statement.

The design philosophy is that the cqlc library should be as unobtrusive as possible, which also means that it doesn't hold any locks on behalf of the calling application.

One could imagine a scenario whereby the result of the fluent API is somehow cached or memoized to an immutable statement - this might play better in a multi threaded situation.
